### ISSUE TITLE
insertando imagenes en jupyter notebook

### ISSUE THREAD

**Issue by carlosr47** [lbenet/2017-2_TSFisComputacional-1#14]
buenas tardes, ya pude insertar una imagen con la ayuda del siguiente comando:
**![imagen1](./TAREA0.JPG);**
sin embargo, al intentar repetir el comando con una variación para la segunda imagen como lo muestro a continuación:
**![imagen2](./tarea0_1.JPG);**
 me salta el siguiente error:
syntax: "./" is not a unary operator
mi pregunta es, ¿por qué sale eso si anteriormente funcionó?

**Comment by lbenet** [comment]
Puedes subir el notebook para que veamos lo que intentaste hacer? Si quieres escribir un comando en GitHub utiliza una comilla (sencilla) inversa, antes y después del comando.

**Comment by carlosr47** [comment]
`![](./TAREA0.jpg)` la usé una vez y logré insertar la primera imagen, desafortunadamente al repetir el comando en otra línea de texto me marca error, uso lo siguiente:
 `![](./tarea0_1.jpg)`
PD: me aseguré que ambas imagenes se encuentran en el mismo directorio

**Comment by UriAceves** [comment]
Hola Carlos, Luis se refería a esta comilla `

No veo problemas (en principio) con tu comando. Así que debe ser un problema de nombre o de dirección. ¿Podrías hacer un `git push` con el notebook en donde te sale el error para verlo más de cerca?
