### ISSUE TITLE
permiso para subir cambios al repositorio de clase

### ISSUE THREAD

**Issue by carlosr47** [lbenet/2017-2_TSFisComputacional-1#15]
hola, no me está permitiendo subir cambios git, no se si me podrían dar autorización para eso, gracias de antemano.

**Comment by carlosr47** [comment]
no aparezco en la lista de contribuidores del repositorio, ¿que debo hacer?

**Comment by lbenet** [comment]
Esto es justo lo que te explicamos en clase: tú debes subir tus cambios a tu propio fork, y desde ahí hacer el pull-request. Por el momento no apareces en la lista de contribuidores porque no has hecho ninguna contribución, es decir, ningún pull-request tuyo ha sido aceptado.

**Comment by lbenet** [comment]
Cierro este reporte, ya que ya se aclaró.
