### ISSUE TITLE
duda en pull request y git config

### ISSUE THREAD

**Issue by carlosr47** [lbenet/2017-2_TSFisComputacional-1#3]
duda en la tarea 0.
buenas noches, tengo una duda en la parte de configurar mi computadora, en la sintaxis de: git config --global <correo electronico>
inserto mi correo de ciencias y no me lo reconoce como válido, ¿estoy pasando algo por alto?
gracias por su tiempo y que tengan buena noche

**Comment by lbenet** [comment]
> `git config --global user.email "usuario@email_de_verdad.hoy"`

Usaste las comillas?

**Comment by carlosr47** [comment]
ya le puse las comillas, me faltó eso, gracias.
