### ISSUE TITLE
Regla de Simpson

### ISSUE THREAD

**Issue by gitrmora** [lbenet/2017-2_TSFisComputacional-1#33]
Al correr mi programa "simpson(x->3x^2,0.0,1.0,0.125/8)" , me aparece este mensaje UniformScaling{Int64}1*I. ¿Cuál es mi problema?

**Comment by lbenet** [comment]
El problema es que usas como variable para la integral `I`, que resulta que indica eso, un escalamiento uniforme (algo proporcional a la matriz identidad). Vale la pena usar nombres de variables que más o menos representan lo que estás calculando!

**Comment by lbenet** [comment]
Cerrando esto ya que la tarea incluye los cambios apropiados.
