### ISSUE TITLE
generar un vector con tantos elementos que el usuario desee.

### ISSUE THREAD

**Issue by carlosr47** [lbenet/2017-2_TSFisComputacional-1#40]
buenas noches, en la taea2 usé un vector h con valores pequeños para poder usar mejor los limites y así, verificar los errores absolutos, sin embargo, quisiera mejorar esto, en vez de que el usuario introduzca el valor del vector h, quisiera hacer una función que pueda generar un vector elemento por elemento. tengo una idea de que operación debe hacer, sería de la forma h[i]=1/2^i. No obstante, ¿cómo puedo meter esto en un vector?
gracias por su tiempo y que tenga buena noche

**Comment by lbenet** [comment]
Quizás lo más sencillo aquí es que leas lo que hace `linspace` y `logspace`; el segundo es el que buscas.
