### ISSUE TITLE
duda tarea5

### ISSUE THREAD

**Issue by carlosr47** [lbenet/2017-2_TSFisComputacional-1#62]
hola, existe un comando que permita reemplazar un elemento de un vector especificando en cual elemento se quiere cambiar?
tenemos deleteat! que es para borrar un elemento, pero al agregar otro, se trasladan los otros elementos 1 entrada antes, el comando push! que funciona para agregar un elemento pero solo al final del vector original, si tengo cierto vector
q=[1,1,2] y quisiera reemplazar el elemento q[2] por otro numero como 3, para que  quedara de la forma
q=[1,3,2]
existe un comando que haga esto?
gracias por su tiempo

**Comment by lbenet** [comment]
Hola,

esta no es una duda sobre la Tarea 5, sino sobre un aspecto (que hemos visto en clase!) de Julia. 

Respondiendo la pregunta con tu ejemplo:
```julia
julia> q = [1, 1, 2]
3-element Array{Int64,1}:
 1
 1
 2

julia> q[2] = 3
3

julia> q
3-element Array{Int64,1}:
 1
 3
 2

```
