### ISSUE TITLE
duda en el pull request

### ISSUE THREAD

**Issue by carlosr47** [lbenet/2017-2_TSFisComputacional-1#7]
buenas tardes, de nuevo tengo problemas en el pull request, aunque puedo intuir que el problema recide que el repositorio de la clase no está actualizado en mi cuenta, ¿como puedo actualizarlo? traté de hacer git clone con el http de la clase en mi branch master, pero no me lo permite.
gracias por su tiempo y que tengan buen día

**Comment by UriAceves** [comment]
Trata de ser más específico en el problema. ¿Qué intentas? ¿Qué mensaje de error arroja?

**Comment by carlosr47** [comment]
fatal: destination path '2017-2_TSFisComputacional-1' already exists and is not an empty directory.
pese que en el branch en donde me sitúo no he usado el comando

**Comment by UriAceves** [comment]
¿Cómo estás intentando bajar los cambios?, y ¿desde qué carpeta de tu computadora?

**Comment by carlosr47** [comment]
desde mi carpeta de user, en un nuevo branch llamado TAREA0CARLOS

**Comment by UriAceves** [comment]
Vale, necesito que me digas el **comando** que estás usando.

**Comment by carlosr47** [comment]
$ git clone https://github.com/lbenet/2017-2_TSFisComputacional-1.git

**Comment by UriAceves** [comment]
Eso imaginaba. Los cambios se bajan con `git pull nombreDelRemote`

**Comment by lbenet** [comment]
Por un lado, **no** necesitas usar `git clone` si ya clonaste el repositorio; eso es lo que dice el error. Si quieres sincronizar tu copia local con "origin" tienes que hacer `git pull` y si quieres sincronizar tu fork (después de haber sincronizado respecto a origin) debes hacer `git push fork`, donde "fork" (sin comillas) corresponde al alias que le diste a tu fork.

Por favor, revisa con cuidado el [notebook sobre git](https://github.com/lbenet/2017-2_TSFisComputacional-1/blob/master/notas_clase/01_Microtutorial_git.ipynb), ya que sí creo que estas cosas se describen ahí.

**Comment by lbenet** [comment]
Otra cosa: vale la pena explotar markdown; por ejemplo, utiliza comillas sencillas inversas cuando escribas código.
