### ISSUE TITLE
Duda sobre el envio de la tarea 0

### ISSUE THREAD

**Issue by H-Cote** [lbenet/2017-2_TSFisComputacional-1#8]
Hola, buenos días.

Quisiera saber cómo puedo subir la tarea a mi fork. 

Primero cloné el repositorio del curso y después actualicé mi fork escribiendo git push origin2 (origin2 es el alias). En el clon del repositorio (el que está en mi máquina), en la carpeta "tareas" hice una carpeta con mi nombre, en la cual, puse las capturas de pantalla. Estando en una nueva rama llamada "tarea0", escribí nuevamente git push origin2, esperando que la nueva carpeta con las capturas se subieran a mi fork, y ya ahí hacer el Pull request, pero no fue así. 

¿Qué es lo que tengo que hacer para enviar la tarea correctamente?

Gracias

Saludos

Héctor

**Comment by lbenet** [comment]
En efecto, viendo tu fork (`origin2`) lo último que se actualizó fue lo que vimos en clase el martes. Veo que hay tres ramas, una de ellas es `tarea0`, y ésta está a la par con `lbenet:master` (rama master del repositorio del curso). 

Mi pregunta es si hiciste `git add` y `git commit` para que git siga los cambios que hiciste? Después de hacer esto es cuando haces `git push origin2`.

**Comment by H-Cote** [comment]
No, no los hice. ¿Debo añadir las capturas de pantalla con git add?

**Comment by lbenet** [comment]
Si no lo haces, git no registra los cambios y sólo éstos se quedan en tu computadora.

> ¿Debo añadir las capturas de pantalla con git add?

Sí

**Comment by H-Cote** [comment]
Ya quedó. 

Muchas gracias
